// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BasePacketsProto.proto

package com.server.classload.packetproto;

public final class PacketSet {
  private PacketSet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BasePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoconf.BasePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 packetId = 1 [default = 0];</code>
     */
    boolean hasPacketId();
    /**
     * <code>optional int32 packetId = 1 [default = 0];</code>
     */
    int getPacketId();

    /**
     * <code>optional bytes packetData = 2;</code>
     */
    boolean hasPacketData();
    /**
     * <code>optional bytes packetData = 2;</code>
     */
    com.google.protobuf.ByteString getPacketData();
  }
  /**
   * Protobuf type {@code protoconf.BasePacket}
   */
  public static final class BasePacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protoconf.BasePacket)
      BasePacketOrBuilder {
    // Use BasePacket.newBuilder() to construct.
    private BasePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BasePacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BasePacket defaultInstance;
    public static BasePacket getDefaultInstance() {
      return defaultInstance;
    }

    public BasePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BasePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packetId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              packetData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.classload.packetproto.PacketSet.internal_static_protoconf_BasePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.classload.packetproto.PacketSet.internal_static_protoconf_BasePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.classload.packetproto.PacketSet.BasePacket.class, com.server.classload.packetproto.PacketSet.BasePacket.Builder.class);
    }

    public static com.google.protobuf.Parser<BasePacket> PARSER =
        new com.google.protobuf.AbstractParser<BasePacket>() {
      public BasePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BasePacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BasePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PACKETID_FIELD_NUMBER = 1;
    private int packetId_;
    /**
     * <code>optional int32 packetId = 1 [default = 0];</code>
     */
    public boolean hasPacketId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 packetId = 1 [default = 0];</code>
     */
    public int getPacketId() {
      return packetId_;
    }

    public static final int PACKETDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString packetData_;
    /**
     * <code>optional bytes packetData = 2;</code>
     */
    public boolean hasPacketData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes packetData = 2;</code>
     */
    public com.google.protobuf.ByteString getPacketData() {
      return packetData_;
    }

    private void initFields() {
      packetId_ = 0;
      packetData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, packetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, packetData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, packetData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.BasePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.classload.packetproto.PacketSet.BasePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoconf.BasePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoconf.BasePacket)
        com.server.classload.packetproto.PacketSet.BasePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_BasePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_BasePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.classload.packetproto.PacketSet.BasePacket.class, com.server.classload.packetproto.PacketSet.BasePacket.Builder.class);
      }

      // Construct using com.server.classload.packetproto.PacketSet.BasePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        packetId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        packetData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_BasePacket_descriptor;
      }

      public com.server.classload.packetproto.PacketSet.BasePacket getDefaultInstanceForType() {
        return com.server.classload.packetproto.PacketSet.BasePacket.getDefaultInstance();
      }

      public com.server.classload.packetproto.PacketSet.BasePacket build() {
        com.server.classload.packetproto.PacketSet.BasePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.classload.packetproto.PacketSet.BasePacket buildPartial() {
        com.server.classload.packetproto.PacketSet.BasePacket result = new com.server.classload.packetproto.PacketSet.BasePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packetId_ = packetId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packetData_ = packetData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.classload.packetproto.PacketSet.BasePacket) {
          return mergeFrom((com.server.classload.packetproto.PacketSet.BasePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.classload.packetproto.PacketSet.BasePacket other) {
        if (other == com.server.classload.packetproto.PacketSet.BasePacket.getDefaultInstance()) return this;
        if (other.hasPacketId()) {
          setPacketId(other.getPacketId());
        }
        if (other.hasPacketData()) {
          setPacketData(other.getPacketData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.classload.packetproto.PacketSet.BasePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.classload.packetproto.PacketSet.BasePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int packetId_ ;
      /**
       * <code>optional int32 packetId = 1 [default = 0];</code>
       */
      public boolean hasPacketId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 packetId = 1 [default = 0];</code>
       */
      public int getPacketId() {
        return packetId_;
      }
      /**
       * <code>optional int32 packetId = 1 [default = 0];</code>
       */
      public Builder setPacketId(int value) {
        bitField0_ |= 0x00000001;
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 packetId = 1 [default = 0];</code>
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString packetData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes packetData = 2;</code>
       */
      public boolean hasPacketData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes packetData = 2;</code>
       */
      public com.google.protobuf.ByteString getPacketData() {
        return packetData_;
      }
      /**
       * <code>optional bytes packetData = 2;</code>
       */
      public Builder setPacketData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        packetData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes packetData = 2;</code>
       */
      public Builder clearPacketData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packetData_ = getDefaultInstance().getPacketData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoconf.BasePacket)
    }

    static {
      defaultInstance = new BasePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoconf.BasePacket)
  }

  public interface NamePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoconf.NamePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code protoconf.NamePacket}
   */
  public static final class NamePacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protoconf.NamePacket)
      NamePacketOrBuilder {
    // Use NamePacket.newBuilder() to construct.
    private NamePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NamePacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NamePacket defaultInstance;
    public static NamePacket getDefaultInstance() {
      return defaultInstance;
    }

    public NamePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NamePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.classload.packetproto.PacketSet.internal_static_protoconf_NamePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.classload.packetproto.PacketSet.internal_static_protoconf_NamePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.classload.packetproto.PacketSet.NamePacket.class, com.server.classload.packetproto.PacketSet.NamePacket.Builder.class);
    }

    public static com.google.protobuf.Parser<NamePacket> PARSER =
        new com.google.protobuf.AbstractParser<NamePacket>() {
      public NamePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NamePacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NamePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "name";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.NamePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.classload.packetproto.PacketSet.NamePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoconf.NamePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoconf.NamePacket)
        com.server.classload.packetproto.PacketSet.NamePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_NamePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_NamePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.classload.packetproto.PacketSet.NamePacket.class, com.server.classload.packetproto.PacketSet.NamePacket.Builder.class);
      }

      // Construct using com.server.classload.packetproto.PacketSet.NamePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "name";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_NamePacket_descriptor;
      }

      public com.server.classload.packetproto.PacketSet.NamePacket getDefaultInstanceForType() {
        return com.server.classload.packetproto.PacketSet.NamePacket.getDefaultInstance();
      }

      public com.server.classload.packetproto.PacketSet.NamePacket build() {
        com.server.classload.packetproto.PacketSet.NamePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.classload.packetproto.PacketSet.NamePacket buildPartial() {
        com.server.classload.packetproto.PacketSet.NamePacket result = new com.server.classload.packetproto.PacketSet.NamePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.classload.packetproto.PacketSet.NamePacket) {
          return mergeFrom((com.server.classload.packetproto.PacketSet.NamePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.classload.packetproto.PacketSet.NamePacket other) {
        if (other == com.server.classload.packetproto.PacketSet.NamePacket.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.classload.packetproto.PacketSet.NamePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.classload.packetproto.PacketSet.NamePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "name";
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoconf.NamePacket)
    }

    static {
      defaultInstance = new NamePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoconf.NamePacket)
  }

  public interface AgePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoconf.AgePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 age = 1 [default = 10];</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 1 [default = 10];</code>
     */
    int getAge();
  }
  /**
   * Protobuf type {@code protoconf.AgePacket}
   */
  public static final class AgePacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protoconf.AgePacket)
      AgePacketOrBuilder {
    // Use AgePacket.newBuilder() to construct.
    private AgePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AgePacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AgePacket defaultInstance;
    public static AgePacket getDefaultInstance() {
      return defaultInstance;
    }

    public AgePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AgePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              age_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.classload.packetproto.PacketSet.internal_static_protoconf_AgePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.classload.packetproto.PacketSet.internal_static_protoconf_AgePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.classload.packetproto.PacketSet.AgePacket.class, com.server.classload.packetproto.PacketSet.AgePacket.Builder.class);
    }

    public static com.google.protobuf.Parser<AgePacket> PARSER =
        new com.google.protobuf.AbstractParser<AgePacket>() {
      public AgePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AgePacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AgePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <code>optional int32 age = 1 [default = 10];</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 age = 1 [default = 10];</code>
     */
    public int getAge() {
      return age_;
    }

    private void initFields() {
      age_ = 10;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, age_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.classload.packetproto.PacketSet.AgePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.classload.packetproto.PacketSet.AgePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoconf.AgePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoconf.AgePacket)
        com.server.classload.packetproto.PacketSet.AgePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_AgePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_AgePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.classload.packetproto.PacketSet.AgePacket.class, com.server.classload.packetproto.PacketSet.AgePacket.Builder.class);
      }

      // Construct using com.server.classload.packetproto.PacketSet.AgePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        age_ = 10;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.classload.packetproto.PacketSet.internal_static_protoconf_AgePacket_descriptor;
      }

      public com.server.classload.packetproto.PacketSet.AgePacket getDefaultInstanceForType() {
        return com.server.classload.packetproto.PacketSet.AgePacket.getDefaultInstance();
      }

      public com.server.classload.packetproto.PacketSet.AgePacket build() {
        com.server.classload.packetproto.PacketSet.AgePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.classload.packetproto.PacketSet.AgePacket buildPartial() {
        com.server.classload.packetproto.PacketSet.AgePacket result = new com.server.classload.packetproto.PacketSet.AgePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.classload.packetproto.PacketSet.AgePacket) {
          return mergeFrom((com.server.classload.packetproto.PacketSet.AgePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.classload.packetproto.PacketSet.AgePacket other) {
        if (other == com.server.classload.packetproto.PacketSet.AgePacket.getDefaultInstance()) return this;
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.classload.packetproto.PacketSet.AgePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.classload.packetproto.PacketSet.AgePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ = 10;
      /**
       * <code>optional int32 age = 1 [default = 10];</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 age = 1 [default = 10];</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 1 [default = 10];</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000001;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 1 [default = 10];</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 10;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoconf.AgePacket)
    }

    static {
      defaultInstance = new AgePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoconf.AgePacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoconf_BasePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoconf_BasePacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoconf_NamePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoconf_NamePacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoconf_AgePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoconf_AgePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026BasePacketsProto.proto\022\tprotoconf\"5\n\nB" +
      "asePacket\022\023\n\010packetId\030\001 \001(\005:\0010\022\022\n\npacket" +
      "Data\030\002 \001(\014\" \n\nNamePacket\022\022\n\004name\030\001 \001(\t:\004" +
      "name\"\034\n\tAgePacket\022\017\n\003age\030\001 \001(\005:\00210B-\n co" +
      "m.server.classload.packetprotoB\tPacketSe" +
      "t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protoconf_BasePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoconf_BasePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protoconf_BasePacket_descriptor,
        new java.lang.String[] { "PacketId", "PacketData", });
    internal_static_protoconf_NamePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protoconf_NamePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protoconf_NamePacket_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_protoconf_AgePacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protoconf_AgePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protoconf_AgePacket_descriptor,
        new java.lang.String[] { "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
